### ISSUE TITLE
Обновление версии + Interlingual Index

### ISSUE THREAD

**Issue by vts3rss** [avidale/python-ruwordnet#2]
Здравствуйте, можете ли Вы обновить данные до версии RuWordNet 2.0, а также добавить поддержку Interlingual Index или идентификаторов английского WordNet, которые есть на сайте RuWordNet? Спасибо.

**Comment by avidale** [comment]
Добрый день!
У меня нет доступа к данным RuWordNet 2.0.
Если вы запросите их на сайте корпуса (https://ruwordnet.ru/ru) и согласуете их публикацию, я готов помочь с заливкой этих данных в `python-ruwordnet`.

**Comment by vts3rss** [comment]
Я свяжусь с авторами для уточнения этого вопроса

**Comment by vts3rss** [comment]
Я получил разрешение. Дополнительную информацию отправил на Вашу почту dale.david@mail.ru. Письмо называется "Данные RuWordNet 2"

**Comment by avidale** [comment]
@vts3rss Данные получил, постараюсь на этой неделе их добавить в обёртку. 
Но я сразу предупреждаю, что полученные данные не совсем совпадают с тем, что сейчас есть на сайте ruwordnet. 
В частности, айдишники у ILI другие: например, для "потенциал" на сайте межъязыковой id равен [i97996](http://wordnet-rdf.princeton.edu/ili/i97996), а в выгруженном xml файле для этого же синсета приведён айди 11493827-n.  Есть ли между ними какое-то соответствие, я не знаю.

**Comment by avidale** [comment]
@vts3rss залил данные (обновление в #3). Предлагаю обновить версию пакета и попробовать)

**Comment by vts3rss** [comment]
В это воскресенье у меня будет больше времени, я попробую и дам фидбек

**Comment by vts3rss** [comment]
Добрый день. 
Все работает, спасибо!
У меня дополнительный вопрос.
Есть ли возможность получить синсет или смысл по его id, русскому и ili? Что-то вроде wn.get_synset_by_ru_id('русский id'), wn.get_wnsynset_by_ili('английский ili'). Или нужно проходить в цикле for по абсолютно всем синсетам и выбирать через if те, у которых есть нужный русский или английский id?

**Comment by avidale** [comment]
Для русских синсетов уже сейчас работает `wn['132821-N'] `. Для английских я тоже сделаю скоро.

**Comment by vts3rss** [comment]
Все понял, буду следить за обновлениями. Еще раз спасибо.

**Comment by avidale** [comment]
А прямо сейчас можно sql-подобный запрос кинуть: `wn.session.query(WNSynset).filter_by(id=query_id).first()`

**Comment by vts3rss** [comment]
Я пока плохо знаком с sqlalchemy. Попробовал запустить вот так, была ошибка. Видимо нужно что-то импортировать, либо что-то еще.
wn.session.query(WNSynset).filter_by(id="10332385-n").first()

**Comment by avidale** [comment]
@vts3rss Я добавил в 0.0.5 версии пакета несколько методов для поиска по тезаурусу. 
Их описание тут: https://github.com/avidale/python-ruwordnet#поиск-в-тезаурусе

На этом данный топик считаю закрытым. Если будут ещё вопросы, открывайте новые issues.

@vts3rss Спасибо большое за проявленную инициативу! :-)

**Comment by avidale** [comment]
Done

**Comment by vts3rss** [comment]
11493827-n это айдишник английского WordNet 3.0. Лично для меня важно чтобы
можно было по английскому идентификатору получить русские данные и
наоборот.
Спасибо за Вашу работу

ср, 14 сент. 2022 г., 03:19 David Dale ***@***.***>:

**Comment by zarkua** [comment]
@avidale @vts3rss простите я так и не понял как получить данные с ntlk или wn. Есть ли какое-то соответствие cili или 11493827-n таким индексам?

**Comment by avidale** [comment]
@zarkua Тут ничего нет про nltk, и я не знаю, что такое cili.
Этот пакет - просто питоновский интерфейс вокруг данных https://github.com/avidale/python-ruwordnet/tree/master/data/rwn-2021, выгруженных с сайта ruwordnet.ru. Каким образом там был получен interlingual index, я понятия не имею.
